// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: movie/movie.proto

package movie

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Duration      int32                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	AgeLimit      int32                  `protobuf:"varint,5,opt,name=age_limit,json=ageLimit,proto3" json:"age_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMovieRequest) Reset() {
	*x = CreateMovieRequest{}
	mi := &file_movie_movie_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMovieRequest) ProtoMessage() {}

func (x *CreateMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_movie_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMovieRequest.ProtoReflect.Descriptor instead.
func (*CreateMovieRequest) Descriptor() ([]byte, []int) {
	return file_movie_movie_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMovieRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateMovieRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateMovieRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateMovieRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *CreateMovieRequest) GetAgeLimit() int32 {
	if x != nil {
		return x.AgeLimit
	}
	return 0
}

type CreateMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMovieResponse) Reset() {
	*x = CreateMovieResponse{}
	mi := &file_movie_movie_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMovieResponse) ProtoMessage() {}

func (x *CreateMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_movie_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMovieResponse.ProtoReflect.Descriptor instead.
func (*CreateMovieResponse) Descriptor() ([]byte, []int) {
	return file_movie_movie_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMovieResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieRequest) Reset() {
	*x = GetMovieRequest{}
	mi := &file_movie_movie_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieRequest) ProtoMessage() {}

func (x *GetMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_movie_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieRequest.ProtoReflect.Descriptor instead.
func (*GetMovieRequest) Descriptor() ([]byte, []int) {
	return file_movie_movie_proto_rawDescGZIP(), []int{2}
}

func (x *GetMovieRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Duration      int32                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	AgeLimit      int32                  `protobuf:"varint,5,opt,name=age_limit,json=ageLimit,proto3" json:"age_limit,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieResponse) Reset() {
	*x = GetMovieResponse{}
	mi := &file_movie_movie_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieResponse) ProtoMessage() {}

func (x *GetMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_movie_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieResponse.ProtoReflect.Descriptor instead.
func (*GetMovieResponse) Descriptor() ([]byte, []int) {
	return file_movie_movie_proto_rawDescGZIP(), []int{3}
}

func (x *GetMovieResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetMovieResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetMovieResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetMovieResponse) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *GetMovieResponse) GetAgeLimit() int32 {
	if x != nil {
		return x.AgeLimit
	}
	return 0
}

func (x *GetMovieResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMovieRequest) Reset() {
	*x = ListMovieRequest{}
	mi := &file_movie_movie_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMovieRequest) ProtoMessage() {}

func (x *ListMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_movie_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMovieRequest.ProtoReflect.Descriptor instead.
func (*ListMovieRequest) Descriptor() ([]byte, []int) {
	return file_movie_movie_proto_rawDescGZIP(), []int{4}
}

type ListMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movies        []*GetMovieResponse    `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"` // []GetMovieResponse
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMovieResponse) Reset() {
	*x = ListMovieResponse{}
	mi := &file_movie_movie_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMovieResponse) ProtoMessage() {}

func (x *ListMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_movie_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMovieResponse.ProtoReflect.Descriptor instead.
func (*ListMovieResponse) Descriptor() ([]byte, []int) {
	return file_movie_movie_proto_rawDescGZIP(), []int{5}
}

func (x *ListMovieResponse) GetMovies() []*GetMovieResponse {
	if x != nil {
		return x.Movies
	}
	return nil
}

type UpdateMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Duration      int32                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	AgeLimit      int32                  `protobuf:"varint,5,opt,name=age_limit,json=ageLimit,proto3" json:"age_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMovieRequest) Reset() {
	*x = UpdateMovieRequest{}
	mi := &file_movie_movie_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMovieRequest) ProtoMessage() {}

func (x *UpdateMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_movie_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMovieRequest.ProtoReflect.Descriptor instead.
func (*UpdateMovieRequest) Descriptor() ([]byte, []int) {
	return file_movie_movie_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMovieRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMovieRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateMovieRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateMovieRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *UpdateMovieRequest) GetAgeLimit() int32 {
	if x != nil {
		return x.AgeLimit
	}
	return 0
}

type UpdateMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMovieResponse) Reset() {
	*x = UpdateMovieResponse{}
	mi := &file_movie_movie_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMovieResponse) ProtoMessage() {}

func (x *UpdateMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_movie_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMovieResponse.ProtoReflect.Descriptor instead.
func (*UpdateMovieResponse) Descriptor() ([]byte, []int) {
	return file_movie_movie_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateMovieResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateMovieResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMovieRequest) Reset() {
	*x = DeleteMovieRequest{}
	mi := &file_movie_movie_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMovieRequest) ProtoMessage() {}

func (x *DeleteMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movie_movie_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMovieRequest.ProtoReflect.Descriptor instead.
func (*DeleteMovieRequest) Descriptor() ([]byte, []int) {
	return file_movie_movie_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteMovieRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteMovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMovieResponse) Reset() {
	*x = DeleteMovieResponse{}
	mi := &file_movie_movie_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMovieResponse) ProtoMessage() {}

func (x *DeleteMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_movie_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMovieResponse.ProtoReflect.Descriptor instead.
func (*DeleteMovieResponse) Descriptor() ([]byte, []int) {
	return file_movie_movie_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteMovieResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteMovieResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_movie_movie_proto protoreflect.FileDescriptor

const file_movie_movie_proto_rawDesc = "" +
	"\n" +
	"\x11movie/movie.proto\x12\x05movie\"\x95\x01\n" +
	"\x12CreateMovieRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x05R\bduration\x12\x1b\n" +
	"\tage_limit\x18\x05 \x01(\x05R\bageLimit\"%\n" +
	"\x13CreateMovieResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"!\n" +
	"\x0fGetMovieRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xb2\x01\n" +
	"\x10GetMovieResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x05R\bduration\x12\x1b\n" +
	"\tage_limit\x18\x05 \x01(\x05R\bageLimit\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"\x12\n" +
	"\x10ListMovieRequest\"D\n" +
	"\x11ListMovieResponse\x12/\n" +
	"\x06movies\x18\x01 \x03(\v2\x17.movie.GetMovieResponseR\x06movies\"\x95\x01\n" +
	"\x12UpdateMovieRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x05R\bduration\x12\x1b\n" +
	"\tage_limit\x18\x05 \x01(\x05R\bageLimit\"C\n" +
	"\x13UpdateMovieResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"$\n" +
	"\x12DeleteMovieRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"C\n" +
	"\x13DeleteMovieResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xc8\x02\n" +
	"\fMovieService\x12?\n" +
	"\x06Create\x12\x19.movie.CreateMovieRequest\x1a\x1a.movie.CreateMovieResponse\x12:\n" +
	"\aGetByID\x12\x16.movie.GetMovieRequest\x1a\x17.movie.GetMovieResponse\x129\n" +
	"\x04List\x12\x17.movie.ListMovieRequest\x1a\x18.movie.ListMovieResponse\x12?\n" +
	"\x06Update\x12\x19.movie.UpdateMovieRequest\x1a\x1a.movie.UpdateMovieResponse\x12?\n" +
	"\x06Delete\x12\x19.movie.DeleteMovieRequest\x1a\x1a.movie.DeleteMovieResponseB\bZ\x06movie/b\x06proto3"

var (
	file_movie_movie_proto_rawDescOnce sync.Once
	file_movie_movie_proto_rawDescData []byte
)

func file_movie_movie_proto_rawDescGZIP() []byte {
	file_movie_movie_proto_rawDescOnce.Do(func() {
		file_movie_movie_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_movie_movie_proto_rawDesc), len(file_movie_movie_proto_rawDesc)))
	})
	return file_movie_movie_proto_rawDescData
}

var file_movie_movie_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_movie_movie_proto_goTypes = []any{
	(*CreateMovieRequest)(nil),  // 0: movie.CreateMovieRequest
	(*CreateMovieResponse)(nil), // 1: movie.CreateMovieResponse
	(*GetMovieRequest)(nil),     // 2: movie.GetMovieRequest
	(*GetMovieResponse)(nil),    // 3: movie.GetMovieResponse
	(*ListMovieRequest)(nil),    // 4: movie.ListMovieRequest
	(*ListMovieResponse)(nil),   // 5: movie.ListMovieResponse
	(*UpdateMovieRequest)(nil),  // 6: movie.UpdateMovieRequest
	(*UpdateMovieResponse)(nil), // 7: movie.UpdateMovieResponse
	(*DeleteMovieRequest)(nil),  // 8: movie.DeleteMovieRequest
	(*DeleteMovieResponse)(nil), // 9: movie.DeleteMovieResponse
}
var file_movie_movie_proto_depIdxs = []int32{
	3, // 0: movie.ListMovieResponse.movies:type_name -> movie.GetMovieResponse
	0, // 1: movie.MovieService.Create:input_type -> movie.CreateMovieRequest
	2, // 2: movie.MovieService.GetByID:input_type -> movie.GetMovieRequest
	4, // 3: movie.MovieService.List:input_type -> movie.ListMovieRequest
	6, // 4: movie.MovieService.Update:input_type -> movie.UpdateMovieRequest
	8, // 5: movie.MovieService.Delete:input_type -> movie.DeleteMovieRequest
	1, // 6: movie.MovieService.Create:output_type -> movie.CreateMovieResponse
	3, // 7: movie.MovieService.GetByID:output_type -> movie.GetMovieResponse
	5, // 8: movie.MovieService.List:output_type -> movie.ListMovieResponse
	7, // 9: movie.MovieService.Update:output_type -> movie.UpdateMovieResponse
	9, // 10: movie.MovieService.Delete:output_type -> movie.DeleteMovieResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_movie_movie_proto_init() }
func file_movie_movie_proto_init() {
	if File_movie_movie_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_movie_movie_proto_rawDesc), len(file_movie_movie_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_movie_movie_proto_goTypes,
		DependencyIndexes: file_movie_movie_proto_depIdxs,
		MessageInfos:      file_movie_movie_proto_msgTypes,
	}.Build()
	File_movie_movie_proto = out.File
	file_movie_movie_proto_goTypes = nil
	file_movie_movie_proto_depIdxs = nil
}
